### PR TITLE
feat: support flat config and eslint v9

### PR DESCRIPTION
**Pull request by kazupon**
Issue: #135 

## What Changed

I've supported ESLint flat configuration and eslint v9
This PR has compatible for legacy style configuration and compatible eslint API using.

So to maintain compatibility, we provide a preset with the `flat` namespace.

flat config example is here:
```js
import storybook from 'eslint-plugin-storybook'

export default [
  // add more generic rulesets here, such as:
  // js.configs.recommended,
  ...storybook.configs['flat/recommended'],

  // something ...
]
```

This implementation is based on `eslint-plugin-vue`, which has several presets to support Vue 3 and Vue 2.
docs is here:
https://eslint.vuejs.org/user-guide/#usage

## Checklist

Check the ones applicable to your change:

- [x] Ran `pnpm run update-all`
- [x] Tests are updated
- [x] Documentation is updated

## Change Type

Indicate the type of change your pull request is:

- [ ] `maintenance`
- [x] `documentation`
- [ ] `patch`
- [x] `minor`
- [ ] `major`

@shilman @ndelangen 
I used to help out some with Vue support at Storybook.
https://github.com/storybookjs/storybook/pull/1267
https://github.com/storybookjs/storybook/pull/1477
https://github.com/storybookjs/storybook/pull/1595

I am happy to contribute to storybook for the first time in 7 years again! ☺️

### CODE REVIEW

**Comment by yannbf** [comment]
This is fantastic @kazupon! Thanks a lot for your contribution(s)! Happy to see you're back into contributing. I'll take a look into this PR once I have some focus time here <3

**Comment by shilman** [comment]
@kazupon welcome back & thanks so much for your contribution -- it's great to see you again! 🙌

**Comment by heddn** [comment]
Eslint v9 just was released, making the enhancements here more important.

**Comment by kazupon** [comment]
I've just supported comatibility for eslint v8 and v9

**Comment by yannbf** [comment]
Hey @kazupon sorry for the long time, I was only able to check this now. I created a new PR based on your branch at #156 so that we can get CI checks and canary releases to test out (given that you did the changes via a fork, they were not triggered). Let's continue working from there!

**Pull request closed without merging**
